version: "3"
services:
  db:
    image: "mysql:${MYSQL_TAG}"
    container_name: "mysql-foo"
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    env_file: .env

  wordpress:
    image: "wordpress:${WORDPRESS_TAG}"
    container_name: "wordpress-foo"
    volumes:
      - ./wordpress/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    env_file: .env

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:${PMA_TAG}"
    container_name: "phpmyadmin-foo"
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80
    env_file: .env
